import org.junit.Test;

import server.TimedLRUCache;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'LiviaZhao' at '11/3/16 4:57 PM' with Gradle 2.14.1
 *
 * @author LiviaZhao, @date 11/3/16 4:57 PM
 */
public class TimedLRUCacheTest {
	
	@Test
    public void testAddMethod1() throws InterruptedException {
		TimedLRUCache<Integer> classUnderTest = new TimedLRUCache<Integer>(5000l);
		classUnderTest.add(3);
		Thread.sleep(2000l);
		assertEquals(classUnderTest.getAll().size(), 1);
		classUnderTest.add(4);
		classUnderTest.add(5);
		assertEquals(classUnderTest.getAll().size(), 3);
		Thread.sleep(2000l);
		assertEquals(classUnderTest.getAll().size(), 3);
		Thread.sleep(2000l);
		assertEquals(classUnderTest.getAll().size(), 2);
		Thread.sleep(2000l);
		assertEquals(classUnderTest.getAll().size(), 0);
    }
	
    @Test 
    public void testAddMethod2() throws InterruptedException {
        TimedLRUCache<Integer> classUnderTest = new TimedLRUCache<Integer>(5000l);
        classUnderTest.add(3);
        classUnderTest.add(4);
        assertEquals(classUnderTest.getAll().size(), 2);
        Thread.sleep(1000l);
        classUnderTest.add(5);
        assertEquals(classUnderTest.getAll().size(), 3);
        Thread.sleep(5000l);
        assertEquals(classUnderTest.getAll().size(), 0);
    }
    
    @Test 
    public void testAddMethod3() throws InterruptedException {
        TimedLRUCache<Integer> classUnderTest = new TimedLRUCache<Integer>(5000l);
        classUnderTest.add(3);
        assertEquals(classUnderTest.getAll().size(), 1);
        Thread.sleep(5000l);
        assertEquals(classUnderTest.getAll().size(), 0);
    }
    
    
}
